"""Stable validation codes."""

from __future__ import annotations

from enum import StrEnum


class ValidationCode(StrEnum):
    MATCH = "MATCH"
    FIELD_ABSENT = "FIELD_ABSENT"
    FIELD_MISSING = "FIELD_MISSING"
    FIELD_UNKNOWN = "FIELD_UNKNOWN"
    FIELD_AMBIGUOUS = "FIELD_AMBIGUOUS"
    VALUE_MISMATCH = "VALUE_MISMATCH"
    FORMAT_INVALID = "FORMAT_INVALID"
    TYPE_INCOMPATIBLE = "TYPE_INCOMPATIBLE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    CROSS_FIELD_CONFLICT = "CROSS_FIELD_CONFLICT"
    NUMERIC_OUT_OF_TOLERANCE = "NUMERIC_OUT_OF_TOLERANCE"
    ALLOWLIST_MISS = "ALLOWLIST_MISS"
    RULE_EXPRESSION_INVALID = "RULE_EXPRESSION_INVALID"
    JUDGMENT_UNCERTAIN = "JUDGMENT_UNCERTAIN"
    JUDGMENT_MATCH = "JUDGMENT_MATCH"
    JUDGMENT_MISMATCH = "JUDGMENT_MISMATCH"
    LLM_OVERRIDE_BLOCKED = "LLM_OVERRIDE_BLOCKED"
    LLM_MALFORMED = "LLM_MALFORMED"
    LLM_TIMEOUT = "LLM_TIMEOUT"
    LLM_PROVIDER_FAILURE = "LLM_PROVIDER_FAILURE"
    LLM_RETRY_EXHAUSTED = "LLM_RETRY_EXHAUSTED"
    EXTRACTION_INVALID = "EXTRACTION_INVALID"
    ENGINE_TIMEOUT = "ENGINE_TIMEOUT"
    PERSISTENCE_FAILURE = "PERSISTENCE_FAILURE"
    UNSUPPORTED_OP = "UNSUPPORTED_OP"
    CROSS_DOCUMENT_DEFERRED = "CROSS_DOCUMENT_DEFERRED"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
