"""Reason / safety constraint code constants for routing."""

from __future__ import annotations

# Safety constraints (non-bypassable)
SC_VALIDATION_FAILED = "SC_VALIDATION_FAILED"
SC_EXTRACTION_FAILED = "SC_EXTRACTION_FAILED"
SC_EXTRACTION_PARTIAL = "SC_EXTRACTION_PARTIAL"
SC_BLOCKING_MISMATCH = "SC_BLOCKING_MISMATCH"
SC_BLOCKING_UNCERTAIN = "SC_BLOCKING_UNCERTAIN"
SC_MISSING_FIELD = "SC_MISSING_FIELD"
SC_UNKNOWN_FIELD = "SC_UNKNOWN_FIELD"
SC_AMBIGUOUS_FIELD = "SC_AMBIGUOUS_FIELD"
SC_LOW_CONFIDENCE = "SC_LOW_CONFIDENCE"
SC_MISSING_EVIDENCE = "SC_MISSING_EVIDENCE"
SC_EMPTY_CHECKS = "SC_EMPTY_CHECKS"
SC_AGENT_FAILURE = "SC_AGENT_FAILURE"
SC_LLM_FAILURE = "SC_LLM_FAILURE"
SC_MALFORMED_OUTPUT = "SC_MALFORMED_OUTPUT"
SC_TIMEOUT = "SC_TIMEOUT"
SC_POLICY_DENY_UNKNOWN = "SC_POLICY_DENY_UNKNOWN"
SC_UNSAFE_LLM_OVERRIDE = "SC_UNSAFE_LLM_OVERRIDE"
SC_CONTRADICTORY_INPUTS = "SC_CONTRADICTORY_INPUTS"
SC_PROMPT_INJECTION_IGNORED = "SC_PROMPT_INJECTION_IGNORED"
SC_FABRICATED_EVIDENCE = "SC_FABRICATED_EVIDENCE"
SC_SYSTEM_FAILSAFE = "SC_SYSTEM_FAILSAFE"
SC_CONFLICTING_EVIDENCE = "SC_CONFLICTING_EVIDENCE"

# Positive / policy reason codes
RC_ALL_BLOCKING_MATCH = "RC_ALL_BLOCKING_MATCH"
RC_HIGH_CONFIDENCE = "RC_HIGH_CONFIDENCE"
RC_AMENDMENT_FROM_MISMATCH = "RC_AMENDMENT_FROM_MISMATCH"
RC_HUMAN_REVIEW_DEFAULT = "RC_HUMAN_REVIEW_DEFAULT"
RC_GRAY_ZONE_LLM_ASSIST = "RC_GRAY_ZONE_LLM_ASSIST"
RC_IDEMPOTENT_REPLAY = "RC_IDEMPOTENT_REPLAY"

ROUTER_AGENT_VERSION = "router-1.0.0"
ROUTER_POLICY_ENGINE_VERSION = "router-policy-1.0.0"
